# Generated by Django 6.0.2 on 2026-03-20 11:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to='documents/', validators=[core.validators.FileSizeValidator(5)]),
        ),
    ]
