# Generated by Django 6.0.2 on 2026-03-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shg', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
