# Generated by Django 6.0.2 on 2026-04-02 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('training', 'Training'), ('production', 'Production'), ('action_required', 'Action Required'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('payment_type', models.CharField(choices=[('installments', 'Installments'), ('full_payment', 'Full Payment')], default='installments', max_length=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], default='online_payment', max_length=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared')], default='pending', max_length=30)),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('public_notes', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_financier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_financier_applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainer_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
